# Generated by Django 5.1.1 on 2024-10-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otentifikasi', '0002_appidentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appidentity',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
