# Generated by Django 5.1.1 on 2024-10-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otentifikasi', '0004_menu_submenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenu',
            name='url',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
