# Generated by Django 5.1.2 on 2024-10-20 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otentifikasi', '0005_submenu_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenu',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='otentifikasi.menu'),
        ),
    ]
