# Generated by Django 5.0 on 2025-03-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otentifikasi', '0006_alter_submenu_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
