# Generated by Django 5.0 on 2025-03-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otentifikasi', '0007_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appidentity',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
