# Generated by Django 5.1.5 on 2025-03-01 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorURL',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('uri', models.CharField(max_length=50)),
                ('security_token', models.TextField()),
                ('ssl', models.BooleanField(default=False)),
                ('format_output', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ScanTable',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('trans_date', models.DateTimeField()),
                ('vehicle_no', models.CharField(blank=True, max_length=50, null=True)),
                ('item', models.CharField(blank=True, max_length=50, null=True)),
                ('po', models.CharField(blank=True, max_length=50, null=True)),
                ('um', models.CharField(blank=True, max_length=50, null=True)),
                ('weighbridge', models.DecimalField(blank=True, decimal_places=2, max_digits=28, null=True)),
                ('silo_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=28, null=True)),
                ('error_by', models.CharField(blank=True, max_length=50, null=True)),
                ('plc_command', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField()),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.vendorurl')),
            ],
        ),
        migrations.CreateModel(
            name='ItemMap',
            fields=[
                ('item_map_id', models.AutoField(primary_key=True, serialize=False)),
                ('internal_item_id', models.CharField(max_length=50)),
                ('external_item_id', models.CharField(max_length=50)),
                ('created_by', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField()),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.vendorurl')),
            ],
        ),
    ]
