# Generated by Django 5.1.5 on 2025-03-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpicorPO',
            fields=[
                ('ponum', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('detail_data', models.JSONField(help_text='Data detail dari PO Check (JSON)')),
                ('summary_data', models.JSONField(help_text='Data summary dari PO Check (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValveOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valve_number', models.PositiveSmallIntegerField(help_text='Nomor valve (1 s/d 6)')),
                ('command_value', models.IntegerField(default=0, help_text='Nilai perintah (0 untuk membuka)')),
                ('status_value', models.IntegerField(blank=True, help_text='Nilai status valve setelah eksekusi', null=True)),
                ('status', models.CharField(help_text='Deskripsi status (misal: Terbuka atau Tertutup)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
