# Generated by Django 5.1.5 on 2025-03-02 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_epicorpo_user_valveoperation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingPipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valve_number', models.PositiveSmallIntegerField(help_text='Nomor valve (1 s/d ???)')),
                ('part_number', models.CharField(blank=True, max_length=255, null=True)),
                ('status_value_number', models.IntegerField(blank=True, help_text='Nilai status valve setelah eksekusi', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='valveoperation',
            name='valve_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.mappingpipa'),
        ),
    ]
