# Generated by Django 5.1.5 on 2025-03-02 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_mappingpipa_alter_valveoperation_valve_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MappingPipa',
            new_name='MappingValve',
        ),
    ]
