# Generated by Django 5.0 on 2025-03-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_rename_mappingpipa_mappingvalve'),
    ]

    operations = [
        migrations.AddField(
            model_name='epicorpo',
            name='status',
            field=models.CharField(default='Open Valve', help_text='Status PO: Open Valve, Selesai, Pause', max_length=50),
        ),
    ]
