# Generated by Django 5.0 on 2025-03-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_epicorpo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epicorpo',
            name='status',
            field=models.CharField(default='IDEM', help_text='Status PO: Open Valve, Selesai, Pause', max_length=50),
        ),
    ]
