# Generated by Django 5.0 on 2025-03-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_epicorpo_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValveSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valve_number', models.PositiveSmallIntegerField(help_text='Nomor valve (1 s/d ???)')),
                ('status', models.PositiveSmallIntegerField(help_text='Nomor 0 or 1')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
