# Generated by Django 6.0 on 2025-12-10 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_valveset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModbusConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('android_ip', models.GenericIPAddressField(default='0.0.0.0', help_text='IP Address Android/Server (0.0.0.0 = semua interface)')),
                ('android_port', models.PositiveIntegerField(default=9502, help_text='Port Modbus Server (recommend: 9502+ untuk Android)')),
                ('plc_ip', models.GenericIPAddressField(default='192.168.2.99', help_text='IP Address PLC (Modbus Master)')),
                ('plc_port', models.PositiveIntegerField(default=502, help_text='Port PLC (biasanya 502 untuk Modbus)')),
                ('auto_start', models.BooleanField(default=False, help_text='Auto-start Modbus server saat aplikasi dijalankan')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modbus Configuration',
                'verbose_name_plural': 'Modbus Configuration',
            },
        ),
    ]
